spring.application.name=acs

management.endpoint.health.probes.enabled=true


management.health.cassandra.enabled=false

# Postgres Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/acs_db}
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:acs_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:acs_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Settings
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.redis.cacheTtl=3600
search.result.redis.ttl = 36000


# Elastic Search Settings
elasticsearch.host=${ELASTICSEARCH_HOST:localhost}
elasticsearch.port=${ELASTICSEARCH_PORT:9200}
elasticsearch.username=${ELASTICSEARCH_USERNAME:elastic}
elasticsearch.password=${ELASTICSEARCH_PASSWORD:changeme}

#Application Specific
search.string.max.regex.length=50
elastic.required.field.sample.json.path=
# elastic.required.field.oascroptype.json.path=/EsFieldsmapping/esOascroptypeRequiredFields.json
# elastic.required.field.oascropcategory.json.path=/EsFieldsmapping/esOascropcategoryRequiredFields.json
# elastic.required.field.oasseason.json.path=/EsFieldsmapping/esOasseasonRequiredFields.json
# elastic.required.field.oascropvariety.json.path=/EsFieldsmapping/esOascropvarietyRequiredFields.json
# elastic.required.field.oaspesticide.json.path=/EsFieldsmapping/esOaspesticideRequiredFields.json
# elastic.required.field.oasinsectiside.json.path=/EsFieldsmapping/esOasinsectisideRequiredFields.json
# elastic.required.field.oasfertilizer.json.path=/EsFieldsmapping/esOasfertilizerRequiredFields.json
# elastic.required.field.oassoil.json.path=/EsFieldsmapping/esOassoilRequiredFields.json
# elastic.required.field.testthree.json.path=/EsFieldsmapping/esTestthreeRequiredFields.json
elastic.required.field.seed.json.path=/EsFieldsmapping/esSeedRequiredFields.json
elastic.required.field.croptype.json.path=/EsFieldsmapping/esCroptypeRequiredFields.json
elastic.required.field.cropcategory.json.path=/EsFieldsmapping/esCropcategoryRequiredFields.json
elastic.required.field.cropvariety.json.path=/EsFieldsmapping/esCropvarietyRequiredFields.json
elastic.required.field.livestock.json.path=/EsFieldsmapping/esLivestockRequiredFields.json
elastic.required.field.season.json.path=/EsFieldsmapping/esSeasonRequiredFields.json
elastic.required.field.soil.json.path=/EsFieldsmapping/esSoilRequiredFields.json
elastic.required.field.extensionequipment.json.path=/EsFieldsmapping/esExtensionequipmentRequiredFields.json
elastic.required.field.pesticide.json.path=/EsFieldsmapping/esPesticideRequiredFields.json
elastic.required.field.insecticide.json.path=/EsFieldsmapping/esInsecticideRequiredFields.json
elastic.required.field.fertilizer.json.path=/EsFieldsmapping/esFertilizerRequiredFields.json
elastic.required.field.location.json.path=/EsFieldsmapping/esLocationRequiredFields.json
